version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: provisioning/app/Dockerfile
    environment:
      RAILSUSER: '${RAILSUSER}'
    volumes:
      - ../app:/app
    working_dir: /app/blog
    ports:
      - 8080:3000
    command: ["bin/rails", "server"]
